//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseDataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Игра
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Игра()
        {
            this.Корзина = new HashSet<Корзина>();
        }
    
        public int id_игры { get; set; }
        public int id_платформы { get; set; }
        public string Название { get; set; }
        public string Описание { get; set; }
        public string Обложка { get; set; }
        public int Цена { get; set; }
        public System.DateTime Дата_выхода { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Корзина> Корзина { get; set; }
        public virtual Платформа Платформа { get; set; }
    }
}
