//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseDataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ИсторияПокупок
    {
        public string Действие { get; set; }
        public System.DateTime Дата { get; set; }
        public string Пользователь { get; set; }
        public string Игра { get; set; }
    }
}
