//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseDataB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Корзина
    {
        public int id_корзины { get; set; }
        public int id_пользователя { get; set; }
        public int id_игры { get; set; }
        public int Цена { get; set; }
        public System.DateTime Дата { get; set; }
        public string Статус { get; set; }
    
        public virtual Игра Игра { get; set; }
        public virtual Пользователь Пользователь { get; set; }
    }
}
